### PR TITLE
Update 04-tabular_data.md

### PR DESCRIPTION
**Pull request by vincehradil**
Add a carriage return on lines 322 and 355

Please delete this line and the text below before submitting your contribution.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.  

---

### CODE REVIEW

**Comment by janash** [comment]
The newlines here are not necessary. The print function should include newlines automatically.

For example, the code without newlines results in the following for the `water.xyz` file:
```
O to H1 : 0.969
O to H2 : 0.969
```

with a newline character at the end of the `print` statement, 

```
O to H1 : 0.969

O to H2 : 0.969

```

Is there a reason you think newlines need to be included, or are you seeing different behavior?

**Comment by vincehradil** [comment]
You are correct. I was writing to a file. In that case, I need the newlines.

**Comment by janash** [comment]
okay, great. Thanks for looking over and contributing!

**Comment by vincehradil** [comment]
My pleasure. Keep up the good work!

**Pull request closed without merging**
