### PR TITLE
Expand git/GitHub and pytest material

### PR DESCRIPTION
**Pull request by janash**
This PR separates git from GitHub, and expands information in both lessons.

### CODE REVIEW

**Review by armcdona — COMMENTED** [review]
If we want to separate Git and GitHub like this, I think it might be useful to callout to people what they should cover in a truly intro workshop. Because we do think they should introduce at least the very basics of GitHub.  So highlighting a good place to end the lesson or labeling the more complex things as optional extensions, might help people make sense of the materials if they are true beginners.

**Comment by janash** [comment]
Should we also change the order back (pytest first, followed by git and GitHub). I can just add a "time check" to the git portion after the first commit.

**Comment by armcdona** [comment]
Yeah, I think that would be fine.  And then if people skipped pytest all together, that would be fine too.  (I mean, not fine, people love pytest, but you know what I mean.

**Comment by janash** [comment]
Requested changes made.

**Comment by janash** [comment]
I'm going to merge this for now and remove stuff if it's way too much.

**Pull request merged**
